# Generated by Django 3.0.2 on 2020-01-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('area_unit', models.CharField(max_length=10, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(null=True)),
                ('home_size', models.PositiveIntegerField(null=True)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'Single Family'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'Multi Family'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex')], max_length=50, null=True)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.BigIntegerField(null=True)),
                ('link', models.TextField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField(null=True)),
                ('rent_price', models.PositiveIntegerField(null=True)),
                ('rentzestimate_amount', models.PositiveIntegerField(null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
                ('tax_value', models.PositiveIntegerField(null=True)),
                ('tax_year', models.PositiveSmallIntegerField(null=True)),
                ('year_built', models.PositiveSmallIntegerField(null=True)),
                ('zestimate_amount', models.PositiveIntegerField(null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
