# Generated by Django 3.0.2 on 2020-01-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zillowchallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
    ]
