# Generated by Django 3.0.2 on 2020-02-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillowchallenge', '0002_auto_20200131_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.FloatField(null=True),
        ),
    ]
