# Generated by Django 3.0.2 on 2020-02-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zillowchallenge', '0004_auto_20200201_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='ZListing',
        ),
    ]
